### ISSUE TITLE
[Question] 'Fake' Streaming

### ISSUE THREAD

**Issue by Silentz0r** [ScriptSmith/instamancer#13]
Can i use this library to make a 'fake' stream to a user account? 

Like fetching data on new post every X time and if it's a new post get all the photos/videos of the new post? 

Thank you.

**Comment by ScriptSmith** [comment]
This isn't part of Instamancer's core functionality, but you can write something to do it yourself with Instamancer. There may be other instagram tools that do what you're after, but I'm not aware of any.

For a user this is difficult, because Instamancer doesn't retrieve all of a user's most recent posts unless it's in full mode, and posts are returned out of order in full mode. Also, it's kinda wasteful because it would require you to create and destroy a new browser instance each time you want to check for new posts.

Instead, I'd just do this in a loop every _x_ seconds:

1. Make an http request to the user's page on instagram with some http library
2. Parse the data in the line that starts with:
 `<script type="text/javascript">window._sharedData = `
3. Look for new post ids
4. Use `Instamancer.post(ids, options)` to get the data for new posts

**Comment by Silentz0r** [comment]
Thank you for your idea, it's awesome. I'm trying to use your library but im getting this:

```
const Instamancer = require('instamancer');
async function getDataInstagrambyID() {
    let data = await instagramPhotos();
    console.log(Instamancer.post(data[0].node.id))
}
getDataInstagrambyID();
```

console:
`Object [AsyncGenerator] {}`

I didn't install Instamancer globally because i don't need it. I just did `npm i instamancer --save-dev` 

Thank you.

**Comment by ScriptSmith** [comment]
`post(ids, options)` takes an array of posts, your issue with it only accessing `/p/B` is because you're only passing it a single string.

Posts on Instagram have a field called `id` but it can't be used to retrieve posts, so we use the shortcode as the identifier.

Don't worry about global install, that's for the CLI tool.

Adapting your code, it'd look something like this:

```
const Instamancer = require('instamancer');
async function getDataInstagrambyID() {
    const data = await instagramPhotos();
    console.log(Instamancer.post(data.map(post => post.node.shortcode)))
}
getDataInstagrambyID();
```

**Comment by Silentz0r** [comment]
I'm closing this as resolved, sorry for wasting your time on this. It's working now with your code. Thank you very much, have a nice day. I need much to learn.

**Comment by ScriptSmith** [comment]
Great! Don't worry about wasting my time, I'm happy to help.

**Comment by ScriptSmith** [comment]
And if you're a new developer, you might find using something like [Instaloader](https://instaloader.github.io/as-module.html) or [Instalooter](https://instalooter.readthedocs.io/en/latest/instalooter/index.html) to be a bit easier to wrap your head around when you're writing this because there's less async/await involved

**Comment by Silentz0r** [comment]
Thank you, mind you one last question, if i want to use only 1 shortcode (the last one) how can i do that? I only need the recent one to compare if it's a new post.
