### ISSUE TITLE
[FEATURE] Need a step-by-step example

### ISSUE THREAD

**Issue by lkl2050** [ScriptSmith/instamancer#29]
Hi, I am a newbie python web scrapper. I really want to use instamancer to scrape data from instagram but I find it hard to get started. 

Is there any step-by-step example about how to use the package from scratch? For instance, a code snippet that scraps posts from the tag "skateboard" on 2018. 
 
A step-by-step example like this will certainly help newbies like me and make instamancer more popular. 

Thank you very much for your help.

**Comment by ScriptSmith** [comment]
Well in order to use the package itself, you need to learn to use node / typescript.

Once you have a grip on that, you should be able to use the example in the README [here](https://github.com/ScriptSmith/instamancer#module), or the examples in the [examples directory](https://github.com/ScriptSmith/instamancer/tree/master/examples)

**Comment by lkl2050** [comment]
Thank you very much. I will try to learn node / typescript.
On Oct 3, 2019, 18:00 -0400, Adam Smith <notifications@github.com>, wrote:

Well in order to use the package itself, you need to learn to use node / typescript.

Once you have a grip on that, you should be able to use the example in the README here<https://github.com/ScriptSmith/instamancer#module>, or the examples in the examples directory<https://github.com/ScriptSmith/instamancer/tree/master/examples>
