### ISSUE TITLE
get user not work correctly

### ISSUE THREAD

**Issue by juliomontilla100** [ScriptSmith/instamancer#3]
Hi...

I love this library

but I tried this..

const options = Instamancer.IOptions = {
    total: 0
}

let getPost = async () => {
    const userData = Instamancer.user("global_66", options);
    for await (let user of userData) {
        console.log(user);
    }
}

getPost()

"only return 15 scraped posts", but on the ig are 27 post

node v10.15.3

**Comment by ScriptSmith** [comment]
Instamancer works by listening to API requests that an Instagram page makes, and because the page comes pre-loaded with some posts,  these posts are never requested and thus ignored.

If having an exhaustive list of posts from a user is important to you, then you might be better off with another tool. At this stage, I don't plan on modifying Instamancer to extract posts from the first page.

**Comment by ScriptSmith** [comment]
Fized in [v1.4.0](https://github.com/ScriptSmith/instamancer/releases/tag/v1.4.0)

**Comment by juliomontilla100** [comment]
> Fixed in [v1.4.0](https://github.com/ScriptSmith/instamancer/releases/tag/v1.4.0)

perfect!
