### ISSUE TITLE
[BUG] After scraping around 800 hashtags Instamancer reloads the browser

### ISSUE THREAD

**Issue by Daniel-Griffiths** [ScriptSmith/instamancer#35]
**Describe the bug**
When scraping for hashtag's, recently it seem's to fail after scraping around ~800 (this is fairly consistent). When reaching around 800 Instamancer restarts the browser and tries again from scratch.

It seems to be related to this line of code: https://github.com/ScriptSmith/instamancer/blob/07e664ea6b144f6d304c4c2cc2f7e957f53fa4f7/src/api/instagram.ts#L419

Specifically the `this.start()` method which causes the browser to reload.

And by looking at the network logs in chrome I can see that one of the graphql requests returns an error around the 800 post mark. Every other request after this one seems to work ok.

**To Reproduce**
Search for any hashtag, and make sure the limit is higher than 800. 

**Setup (please complete the following information):**
 - OS: [e.g. MacOS Catalina]
 - Instamancer version [e.g. v3.0.1]

I will add more info here as I debug the issue further.

**Comment by ScriptSmith** [comment]
In my initial attempt to reproduce this, I am able to gather 1000 posts from a hashtag.

The restarting process you describe is what I _grafting_, which allows instamancer to perform long scraping jobs by restarting the browser in order to limit resource usage. You can read about it on the [website](https://adamsm.com/instamancer/) and in the [FAQ](https://github.com/ScriptSmith/instamancer/blob/master/FAQ.md#what-happens-if-i-disable-grafting).

This bug could be because when instamancer attempts to perform a graft by swapping request parameters on the fly after being restarted, something is going wrong.

So, a few questions:
- Can you include a copy of the graphql error here so I can see what it says?
- Does the same issue occur when using `-g=false`?
- Does the same issue occur when using a different internet connection?

**Comment by Daniel-Griffiths** [comment]
Hi @ScriptSmith  

Thanks for the detailed response! I didn't event notice the FAQ document, that will be super handy.

From what I recall when grafting was triggered and the browser restarted it started scraping the hashtags from the very beginning which would put it into an infinite loop.

I will confirm this after I finish work and try to get a reproducible example. I will also answer the two questions you posted.

**Comment by Daniel-Griffiths** [comment]
Example failed requests with grafting disabled:

endpoint: https://www.instagram.com/graphql/query/?query_hash=174a5243287c5f3a7de741089750ab3b&variables=%7B%22tag_name%22%3A%22rebelgal%22%2C%22first%22%3A12%2C%22after%22%3A%22QVFCZndxMUV2QXlQalMyTVJ5ZUFqUDVraGRhc20wTmJfNkthMlZYa3kwSGZUODJid3JRWHp6VmQ2VUIxRTRNRWRzU0kzVlVCT0o2VER3SWVmWWl2Z3RHdg%3D%3D%22%7D

![image](https://user-images.githubusercontent.com/1458314/68383560-cbb57d80-014d-11ea-9afa-6713d9f1fe1b.png)

**Comment by ScriptSmith** [comment]
I think that error is caused by chrome cancelling requests due to resource limitations. Try cloning this repo and changing the value of `jumpMod` in `src/api/instagram.ts` to 50. That should cause grafting to be initiated more quickly.

**Comment by ScriptSmith** [comment]
Did you get a chance to try out the fix?

**Comment by Daniel-Griffiths** [comment]
Sorry @ScriptSmith I have not had a chance to try it. I will close this issue for now and reopen if I can get any further info.
