### ISSUE TITLE
Alert from # used in post.

### ISSUE THREAD

**Issue by quintendewilde** [ScriptSmith/instamancer#43]
Is it possible to get an alert from post when the post has a #something in it? 

Or is that already possible at the time of this question? It is very unclear to me if it indeed is possible with the readme..

Regards!

**Comment by ScriptSmith** [comment]
Instamancer is a core tool, not an application.

If you want to use the data it collects to do things like alerting, you should link it with other tools or write a JavaScript program using the instamancer package. 

Here's an example using jq that looks for posts that use the text "dog" while retrieving data from the "cat" hashtag endpoint:

```
instamancer hashtag cat -qc10 -o - | jq 'select(.node.edge_media_to_caption.edges[0].node.text | contains("dog"))'
```

With a bit of scripting and some other tools, you could write something that checks every n minutes for new posts and triggers an email or desktop notification if the posts match a certain condition.

**Comment by quintendewilde** [comment]
Hi yeah I knew it was a tool, I'm not native english, so I used the incorrect term. Apologies!

Thanks for your example, I'm now installing it on my raspberry pi to test the tool out! 

I'm unclear what this means, probably due to my insufficient knowledge of the language or coding.

While retrieving data from the "cat" hashtag endpoint 

So you search for cats in post about dogs? Is that what this means? 

And do you know tools that are alive that can be used open source to alert when a hashtag is used.

Anyways thanks for hitting me back! I can try stuff out now.

**Comment by ScriptSmith** [comment]
> So you search for cats in post about dogs? Is that what this means?

Yes

Regarding your other questions:

What I mean by clarifying that it is a tool rather than an application, is that it's designed to just do one thing: get data from instagram and put it somewhere. Anything else like a user interface, sending alerts etc, is not within this project's scope.

It's not clear what you mean by 'alert'. Does it mean to output to a terminal, send an email, send a push notification to your phone, etc? I don't think there is currently a comprehensive application that will do the latter two for you. And if you're not comfortable writing scripts, then I don't think you'll be able to accomplish what you're after.

Additionally, if you're using a raspberry pi, instamancer might be too heavy as it has to run a web browser in the background. You might be better off with one of the other tools at the bottom of the README. [Link](https://github.com/ScriptSmith/instamancer#comparison)

**Comment by quintendewilde** [comment]
The alert schould translate in an osc message. I know basic programming.
But to create my own API or similar is momentarily beyond my scope.

I used a tool called InstaPY and that worked on the RPi3, so I thought it
would work.

But I can always get it to work on my mac and then send the osc message to
the raspberry pi.

I'll take a look at the readme.
