### ISSUE TITLE
puppeteer dep is huge

### ISSUE THREAD

**Issue by diffractometer** [ScriptSmith/instamancer#5]
Is it possible to use a leaner version of puppeteer?

**Comment by ScriptSmith** [comment]
Puppeteer is big because it uses chromium, and downloads its binary.

This dependency is pretty fixed because there aren't many other packages that can do request interception like instamancer (puppeteer-firefox is close to being compatible), but is likely just as big.

We could transition to puppeteer-core, but instamancer is intended to be used on servers so it makes sense for it to manage the chromium dependency itself.

I can add an additional flag or environment variable to allow you to use a system chromium/chrome binary that has already been installed. And if you use the `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` environment variable when installing instamancer, puppeteer will skip downloading the chromium binary.

**Comment by ScriptSmith** [comment]
You can now use the `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` environment variable before installation, and use the `--browser` flag to specify a path to an existing chromium/chrome installation

**Comment by diffractometer** [comment]
@ScriptSmith thanks! Really cool. I'll check it out asap. This was for a hackathon project so probably later in the week.
